/*
 * H Plus Sports Company API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CustomerApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>List all customers</remarks>
        /// <response code="200">Search results</response>
        [HttpGet]
        [Route("/customer")]
        [ValidateModelState]
        [SwaggerOperation("CustomerGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Customer>), description: "Search results")]
        public virtual IActionResult CustomerGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Customer>));
            string exampleJson = null;
            exampleJson = "[ {\n  \"firstName\" : \"Joe\",\n  \"lastName\" : \"Schmoe\",\n  \"phone\" : \"123-456-7890\",\n  \"id\" : \"isjwyqndj\"\n}, {\n  \"firstName\" : \"Joe\",\n  \"lastName\" : \"Schmoe\",\n  \"phone\" : \"123-456-7890\",\n  \"id\" : \"isjwyqndj\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Customer>>(exampleJson)
                        : default(List<Customer>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Order placed</response>
        [HttpPost]
        [Route("/order")]
        [ValidateModelState]
        [SwaggerOperation("OrderPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Order), description: "Order placed")]
        public virtual IActionResult OrderPost([FromBody]Order body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Order));
            string exampleJson = null;
            exampleJson = "{\n  \"quantity\" : 3,\n  \"itemsPurchased\" : [ {\n    \"imageLink\" : \"https://images.pexels.com/photos/2477379/pexels-photo-2477379.jpeg\",\n    \"name\" : \"Lemon Water\",\n    \"description\" : \"I am tasty water\",\n    \"id\" : 121,\n    \"imageTitle\" : \"Image of Lemon Water\"\n  }, {\n    \"imageLink\" : \"https://images.pexels.com/photos/2477379/pexels-photo-2477379.jpeg\",\n    \"name\" : \"Lemon Water\",\n    \"description\" : \"I am tasty water\",\n    \"id\" : 121,\n    \"imageTitle\" : \"Image of Lemon Water\"\n  } ],\n  \"id\" : \"338\",\n  \"orderDate\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"customer\" : {\n    \"firstName\" : \"Joe\",\n    \"lastName\" : \"Schmoe\",\n    \"phone\" : \"123-456-7890\",\n    \"id\" : \"isjwyqndj\"\n  }\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Order>(exampleJson)
                        : default(Order);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
